import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import SelectSearchParams from "../SelectSearchParams";
import "./globals.css";
import { Link } from "@/i18n/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <main className="relative">
            <header className="absolute w-full flex justify-between">
              <nav>
                <ul className="flex space-x-2.5">
                  <li>
                    <Link
                      href="/"
                      className="block py-2 px-4 rounded-md bg-blue-800 hover:bg-blue-900"
                    >
                      Home
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/about"
                      className="block py-2 px-4 rounded-md bg-blue-800 hover:bg-blue-900"
                    >
                      About
                    </Link>
                  </li>
                </ul>
              </nav>
              <SelectSearchParams route={locale} />
            </header>
            {children}
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
